# Práctica 1
### Ejercicio 3: Ejemplos con Numpy, Matpotlib

---
---
---
### Numpy
#### Crear un array

In [1]:
from numpy import array
a = array([[2.0, -1.0],[-1.0, 3.0]])
print(a)

[[ 2. -1.]
 [-1.  3.]]


In [3]:
b = array([[2, -1],[-1, 3]],float)
print(b)

[[ 2. -1.]
 [-1.  3.]]


#### Función `arange(from, to, increment)`

In [5]:
from numpy import *
print(arange(2,10,2))

[2 4 6 8]


In [6]:
print(arange(2.0,10.0,2.0))

[2. 4. 6. 8.]


In [7]:
print(zeros(3))

[0. 0. 0.]


In [8]:
print(zeros((3),int))

[0 0 0]


In [9]:
print(ones((2,2)))

[[1. 1.]
 [1. 1.]]
