# Práctica 2
---
## Sistemas de ecuaciones lineales¶
### Ejercicio: resolver  con la factorización QR del paquete numpy de la matriz A y verificar resultado


$$A = \begin{bmatrix} 2& -1&2 \\ 1& 6& -1 \\ 1& 4& 1\end{bmatrix}$$
$$B=\begin{bmatrix}7 & -1\\13 & 6\\5 & 7\end{bmatrix}$$


In [40]:
import numpy as np
from pprint import pprint
A = np.array([[2,-1,2], [1,6,-1], [1,4,1]])
B = np.array([[7.,-1.],[13.,6.],[5.,7.]])
Q,R = np.linalg.qr(A)

In [46]:
X = np.dot(np.linalg.inv(R), np.dot(Q.T, B))

In [47]:
print('Verificando resultado AX = B')
print('B:')
pprint(B)
print('AX:')
pprint(A@X)

Verificando resultado AX = B
B:
array([[ 7., -1.],
       [13.,  6.],
       [ 5.,  7.]])
AX:
array([[ 7., -1.],
       [13.,  6.],
       [ 5.,  7.]])


---
### Ejercicio: resolver los sistemas de ecuaciones lineales $Ax = b$ con la factorización P, LU y verificar resultado
### 1)
$$A = \left[\begin{array}{ccc}
0 &1& -1\\
-2 &4& -1\\
-2 &5& -4
\end{array}
\right],
b=
\left[\begin{array}{c}
3\\
1\\
-2
\end{array}
\right] 
$$

In [71]:
import scipy
import scipy.linalg
import numpy as np
from pprint import pprint

A = scipy.array([[0, 1, -1], [-2, 4, -1], [-2, 5, -4]])
b = scipy.array([3,1,-2])
P, L, U = scipy.linalg.lu(A)

In [72]:
print('Usando los factores P,L,U para resolver AX = B')
D = scipy.linalg.solve_triangular(L,P@b,lower=True)
X = scipy.linalg.solve_triangular(U,D)
print('X:')
pprint(X)

Usando los factores P,L,U para resolver AX = B
X:
array([10.,  6.,  3.])


In [73]:
print('Verificando resultado AX = B')
print('b:')
pprint(b)
print('AX:')
pprint(A@X)

Verificando resultado AX = B
b:
array([ 3,  1, -2])
AX:
array([ 3.,  1., -2.])


---
### 2)
$$A = \left[\begin{array}{ccc}
0 &1& -1\\
-2 &4& -1\\
-2 &5& -4
\end{array}
\right],
b=
\left[\begin{array}{c}
-5\\
7\\
0
\end{array}
\right] 
$$

In [74]:
A = scipy.array([[0, 1, -1], [-2, 4, -1], [-2, 5, -4]])
b = scipy.array([-5,7,0])
P, L, U = scipy.linalg.lu(A)
D = scipy.linalg.solve_triangular(L,P@b,lower=True)
X = scipy.linalg.solve_triangular(U,D)
print('X:')
pprint(X)
print('Verificando resultado AX = B')
print('b:')
pprint(b)
print('AX:')
pprint(A@X)

X:
array([-12.,  -4.,   1.])
Verificando resultado AX = B
b:
array([-5,  7,  0])
AX:
array([-5.,  7.,  0.])


---
### 3)
$$A = \left[\begin{array}{cccc}
1 &2& 2\\
2 &5& 7\\
3 &6& 6
\end{array}
\right],
b=
\left[\begin{array}{c}
0\\
0\\
0
\end{array}
\right] 
$$

In [81]:
A = scipy.array([[1,2,2], [2,5,7], [3,6,6]])
b = scipy.array([0,0,0])
P, L, U = scipy.linalg.lu(A)
D = scipy.linalg.solve_triangular(L,P@b,lower=True)
X = scipy.linalg.solve_triangular(U,D)
print('X:')
pprint(X)
print('Verificando resultado AX = B')
print('b:')
pprint(b)
print('AX:')
pprint(A@X)